### ISSUE TITLE
Link on hackage is out-of-date

### ISSUE THREAD

**Issue by wzhd** [kamwitsta/fuzzytime#1]
The [page](https://hackage.haskell.org/package/fuzzytime) still points to https://github.com/caminoix/fuzzytime, which doesn't exist anymore.

**Comment by kamil-stachowski** [comment]
Thanks for letting me know. I don't seem to be able to fix it without uploading a new version, and some of the libraries must have changed since last I looked because now I'm getting errors during compilation. I'll look into it.

**Comment by kamil-stachowski** [comment]
Fixed. Thanks again!
